
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f26/team01-f26-00
owner: ucsb-cs156-f26
repo_name: team01-f26-00
pull_requests: [{"author":{"id":"U_kgDOCMvSuQ","is_bot":false,"login":"keigoomura","name":"Keigo Omura"},"headRefName":"keigoomura-MenuItemReview-CRUD","number":48,"title":"Menu Item Review CRUD Operations","url":"https://github.com/ucsb-cs156-f26/team01-f26-00/pull/48"}]
